server:
  port: 9999

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:2073324498/config-server9999 # github上面的仓库名字
          search-paths:
            - springcloud-config9999 # 搜索目录
      label: master #搜索目录
eureka:
  client:
    register-with-eureka: true # 是否将自己注册到eureka server端
    fetch-registry: true # 是否从eureka server抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true才能配合负载均衡
    service-url:
      defaultZone: http://114.55.176.253:8090/eureka